-- MySQL Script generated by MySQL Workbench
-- Tue Jun  5 02:22:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema brproyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brproyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brproyecto` DEFAULT CHARACTER SET utf8 ;
USE `brproyecto` ;

-- -----------------------------------------------------
-- Table `brproyecto`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brproyecto`.`Cliente` (
  `idCliente` VARCHAR(15) NOT NULL,
  `nombreCliente` VARCHAR(45) NOT NULL,
  `telefonoCliente` VARCHAR(11) NOT NULL,
  `correoCliente` VARCHAR(50) NOT NULL,
  `oficioCliente` VARCHAR(20) NULL,
  `direccionCliente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brproyecto`.`Inmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brproyecto`.`Inmueble` (
  `idProp` INT NOT NULL,
  `ciudadProp` VARCHAR(55) NULL,
  `direccionProp` VARCHAR(65) NULL,
  `descripcion` VARCHAR(180) NULL,
  `tipoInmueble` VARCHAR(45) NULL,
  `precioProp` INT NULL,
  `comisionProp` INT NULL,
  `medidaCProp` INT NULL,
  `banos` INT NULL,
  `dormitorios` INT NULL,
  `foto` LONGBLOB NULL,
  PRIMARY KEY (`idProp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brproyecto`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brproyecto`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `nombreEmpleado` VARCHAR(45) NOT NULL,
  `telefonoEmpleado` VARCHAR(11) NOT NULL,
  `correoEmpleado` VARCHAR(65) NULL,
  `direccionEmpleado` VARCHAR(145) NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brproyecto`.`Operacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brproyecto`.`Operacion` (
  `idOperacion` INT NOT NULL,
  `fechaOperacion` DATETIME NULL,
  `observacionOpeacion` VARCHAR(100) NULL,
  `Cliente_idCliente` VARCHAR(15) NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Propiedad_idProp` INT NOT NULL,
  `FormaPago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOperacion`),
  INDEX `fk_Operacion_Cliente_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Operacion_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  INDEX `fk_Operacion_Inmueble1_idx` (`Propiedad_idProp` ASC),
  UNIQUE INDEX `Propiedad_idProp_UNIQUE` (`Propiedad_idProp` ASC),
  CONSTRAINT `fk_Operacion_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `brproyecto`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operacion_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `brproyecto`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operacion_Inmueble1`
    FOREIGN KEY (`Propiedad_idProp`)
    REFERENCES `brproyecto`.`Inmueble` (`idProp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brproyecto`.`Saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brproyecto`.`Saldo` (
  `idNumeroPago` INT NOT NULL AUTO_INCREMENT,
  `Operacion_idOperacion` INT NOT NULL,
  `Saldo_pagado` INT NULL,
  `saldoPendiente` INT NULL,
  `Descuento` INT NULL,
  `Mora` INT NULL,
  `Interes` INT NULL,
  PRIMARY KEY (`idNumeroPago`),
  INDEX `fk_Saldo_Operacion1_idx` (`Operacion_idOperacion` ASC),
  CONSTRAINT `fk_Saldo_Operacion1`
    FOREIGN KEY (`Operacion_idOperacion`)
    REFERENCES `brproyecto`.`Operacion` (`idOperacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
